version: "3"
services:
  fileserver:
    image: php:7.2.6-apache
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./fileserver:/var/www/html
  md5hasher:
    image: php:7.2.6-apache
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./md5hasher:/var/www/html
  sudanesechildren:
    image: httpd:latest
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./sudanesechildren:/usr/local/apache2/htdocs
  internet:
    image: node:latest
    restart: always
    ports:
      - "8003:8000"
    working_dir: /home/app
    volumes:
      - ./internet:/home/app
    command: "npm start"
  saudi:
    image: httpd:latest
    restart: always
    ports:
      - "8004:80"
    volumes:
      - ./saudi:/usr/local/apache2/htdocs
